jwt:
  secret: sadjkjsldjskaljdklsjdjsalkdjksljadasjlkdjlaskdjasjkldjskljdasjldjaskldjskjjdsdjsgahdghsgdhja
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 123
  jpa:
    hibernate:
    ddl-auto: create-drop
  logging:
    Level:
      org:
        hibernate:
          SQL: DEBUG

